---
- name: Install OS dependencies
  apt:  pkg={{ item }}
        state=latest
        update_cache=yes
  with_items:
    - build-essential
    - git
    - libpcre3-dev
    - nginx-common
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - sysfsutils
  tags:
    - install
    - deps
