---
- name: Clone/Update git repo
  git:  repo=https://github.com/kernelci/kernelci-storage.git
        dest={{ install_base }}/{{ hostname }}
        version={{ git_head }}
        update=yes
  tags:
    - app
    - install

- name: Fix repo permissions
  file: path={{ install_base }}/{{ hostname }}
        state=directory
        recurse=yes
        owner=root
        group=root
  tags:
    - app
    - install

- name: Install pip requirements
  pip:  requirements={{ install_base }}/{{ hostname }}/requirements.txt
        executable=pip3
        virtualenv={{ install_base }}/.venv/{{ hostname }}
        virtualenv_python=python3
        extra_args="--upgrade"
  tags:
    - app
    - install

- name: Fix virtualenv permissions
  file: path={{ install_base }}/.venv/{{ hostname }}
        state=directory
        recurse=yes
        owner=root
        group=root
  tags:
    - app
    - install

- name: Enable KSM (Kernel Samepage Merging)
  file: src=99-ksm.conf
        dest=/etc/sysfs.d/99-ksm.conf
        owner=root
        group=root
        mode=0644
  tags:
    - app
    - install

- name: Does /etc/linaro exists?
  file: path=/etc/linaro/{{ service_name }}
        state=directory
        owner=root
        group=root
        mode=0775
  tags:
    - app
    - install

- name: Install app configuration file
  template: src=kernelci-storage.ini
            dest=/etc/linaro/{{ service_name }}/{{ service_name }}.ini
            owner=root
            group=root
            mode=0644
  notify:
    - reload-kernelci-storage
  tags:
    - app
    - install
    - secrets

- name: Install configuration file
  template: src=kernelci-storage.cfg
            dest=/etc/linaro/{{ service_name }}/{{ service_name }}.cfg
            owner=root
            group=root
            mode=0644
  tags:
    - app
    - install
    - secrets

- name: Install systemd service file
  template: src=kernelci-storage.service
            dest=/etc/systemd/system/{{ service_name }}.service
            owner=root
            group=root
            mode=0644
  notiy:
    - reload-systemd
    - reload-kernelci-storage
  tags:
    - app
    - install
    - systemd

- name: Enable systemd service
  command:  /bin/systemctl enable {{ service_name }}.service
            creates=/etc/systemd/system/multi-user.target.wants/{{ service_name }}.service
  notify:
    - start-kernelci-storage
  tags:
    - app
    - install
    - systemd
