---
- name: start-kernelci-storage
  service:  name={{ service_name }}
            state=started

- name: restart-kernelci-storage
  service:  name={{ service_name }}
            state=restarted

- name: stop-kernelci-storage
  service:  name={{ service_name }}
            state=stopped

- name: reload-kernelci-storage
  service:  name={{ service_name }}
            state=reloaded

- name: reload-systemd
  command: /bin/systemctl daemon-reload
